name: Build Docker images

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Which image(s) to build?'
        required: false
        type: choice
        options:
          - all
          - '["alpine:3.19"]'
          - '["alpine:3.21"]'
          - '["alpine:edge"]'
        default: 'all'

jobs:
  build:
    name: ${{ matrix.base }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: ${{ inputs.image == 'all' && fromJSON('["alpine:3.19", "alpine:3.21", "alpine:edge"]') || fromJSON(inputs.image) }}

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run docker build
        run: docker build --build-arg BASE=${{ matrix.base }} -t ghcr.io/${{ github.repository_owner }}/${{ matrix.base }} .

      - name: Run docker push
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.base }}
